### ISSUE TITLE
Thoughts around Auto Moderation

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-verifier#1]
This is intended as a brain dump of the current thinking.  Let me know what you think...

# New Chocolatey.org user
I think we are going to need a new user created on Chocolatey.org, which the auto-moderation process can use.  Currently we have the ```chocolatey``` user, but he is the maintainer of a number of packages already, and therefore will not be able to moderated them.  We will need another user, who is never a maintainer of any packages.

# Trusted packages
I am of the opinion that even trusted packages should go through the auto-moderation process.  That way, if there are any install/uninstall issues, these will be detected, and reported.  As a result, I think we need to prevent the auto publishing of Trusted packages when they are submitted, and instead, only do this if the auto moderation ends successfully.

# Chocolatey.dll or choco.exe

There is a question over whether we shell out to Choco.exe or take a dependency on the chocolatey.dll.

The service is installed on a server, but the actual testing is going to happen on a few queued up vagrant boxes that don't have the service installed. The verification service will orchestrate getting those boxes in a ready state, passing instructions for things to get installed and then working with the resulting information coming back from those results.

# New Moderation State
Is a new Moderation State for packages required, i.e. AutoModerated?

Given that the auto-moderation user will be doing the exact same thing as an actual moderator, i.e. providing feedback and saving the state of the package (which marks it as Waiting for Maintainer), there should be no requirement for an additional state to be created.  The workflow should be exactly the same as it is currently

# Inspection of package files
Are you planning on using something like Pester to inspect the package files for known common issues?  If so, would these Pester results go into the same gist?

# Gists
The idea is that once a package is auto-moderated, a new gist will be created which will contain the output of the installation, the uninstallation, and also the results of all the package inspections.

When a package goes through multiple rounds of package submissions, I think we should be good citizens and delete the old gists that were previously created, or were you thinking to update the existing gist?

# Package Version properties
Am I right in thinking that we are going to need to add some additional properties to each package version, such as:

* AutoModerationGistUrl
* AutoModerationResult

# How many OS'es are we going to test on?
Eventually we are going to need to test on all platforms that we support, but for now, let's start testing on:

* Windows Server 2012 R2
* Windows 2008 R2

Base images for each of these OS'es will be provisioned for testing using Vagrant

Do we need to test each with different PowerShell versions?  Or would all of them simply have PowerShell 2 as a minimum (or whatever comes with the host OS)

I realise that this is getting a little ahead of where we are, but just wanted to get a feel for what we need.

# Chocolatey Version
Automoderation testing will only be ran against the latest version of Chocolatey.  We will not support the testing of the PowerShell version of Chocolatey.

# Moderation Workflow

* New Package Submitted
* Package is auto-moderated, executing tests on all supported OS'es
* If there are any failures during this process, feedback is submitted to the package version (in the same way as if it were done by a human).  This will cause the package to move to WaitingForMaintainer, and the automated email that is sent out will contain a summary of the problems, as well as a link to the Gist where all the information can be read.  A PacakgeVerification entry will be created for each tested OS, and will be associated with this PackageVersion
* Package Maintainer then corrects issues, re-submits and cycle continues
* If package submissions passes all tests, is somehow marked as ready for human review (this is potentially where we need something to distinguish that it is in this state)
* Moderators then come along and do a sanity check on Package content (which should be much faster, as all the time consuming things will be done at this point)
* If everything is ok, package it set to approved.  Otherwise, email sent to package maintainer, and new package will then get submitted, and cycle repeats.
* In the case of trusted packages, if package is verified, then this package is automatically published to the gallery

# Tasks

- [x] Create new user on Chocolatey.org who will perform auto moderation
- [ ] Create new PackageVerification Table

**Comment by gep13** [comment]
@ferventcoder I will likely edit the above as things change, but what is here just now is just a brain dump of current thinking.  Feel free to edit as well.

**Comment by ferventcoder** [comment]
> How many OS'es are we going to test on?

 Eventually as many as we support, but at first just Windows Server 2012 R2 and Windows 2008 R2.

**Comment by ferventcoder** [comment]
In the Moderation workflow - 

The user that does automatic moderation is still just a user, so they will submit feedback in the same way we do and send an email to the user stating what they need to change, and what the test results were.

**Comment by ferventcoder** [comment]
>Am I right in thinking that we are going to need to add some additional properties to each package version, such as:

> * AutoModerationGistUrl
> * AutoModerationResult

Yes, but keep in mind that this design would only support testing against one platform. We want to test it against several platforms. and I would remove the automoderation word choice.

New table named something like `PackageVerification`.

* AutoModerationResult -> VerificationSuccess - bool
* AutoModerationGistUrl -> VerificationInformation
* PackageVersionId (FK)
* VerificationPlatform (aka windows version)

**Comment by ferventcoder** [comment]
> I think we are going to need a new user created on Chocolatey.org, which the auto-moderation process can use.

Agreed! :+1:

**Comment by ferventcoder** [comment]
> Do we need to test on 0.9.8.33 and the latest Chocolatey?

No. Just new Choco.

**Comment by ferventcoder** [comment]
> Chocolatey.dll or choco.exe? 

Right now I think we want to shell out to choco.exe. Here's why - 

The service is installed on a server, but the actual testing is going to happen on a few queued up vagrant boxes that don't have the service installed.  The verification service will orchestrate getting those boxes in a ready state, passing instructions for things to get installed and then working with the resulting information coming back from those results.

**Comment by ferventcoder** [comment]
> As discussed previously, I think we need an additional state for the moderation state. Once "Submitted" we need to move packages to "AutoModerated" or something, so that they will not be auto moderated again.

We may need an additional state. But I'm not completely sure. We have some added workflow considerations to consider. 

1. The automoderating user sends information about changes that need to occur to the package (this is done in chocolatey.org as the package is submitted). What state do we go in? I believe this is waiting for maintainer.
1. The user fixes based on that feedback, putting the package BACK into a submitted state (waiting for followup though).
1. At some point that before or after the second thing happens, the package is pulled off the queue for the package verifier. After testing, we send the results to chocolatey.org. If it passed, the package is ready for human review (but I foresee a little green light on the right of the name, a red light or a yellow light). If it fails testing, chocolatey.org will follow up with the maintainer again in an email and the package will go back into a waiting for maintainer state.
1. When they submit fixes, we want to test again.

**Comment by gep13** [comment]
>@ferventcoder said...
Yes, but keep in mind that this design would only support testing against one platform. We want to test it against several platforms. and I would remove the automoderation word choice

Good point well made!

**Comment by gep13** [comment]
>@ferventcoder said...
Right now I think we want to shell out to choco.exe.

Makes total sense :+1:

**Comment by gep13** [comment]
@ferventcoder I have updated the original post based on your feedback, and also added a couple other things that occured to me, i.e. tidying up of gists.

I am not sold on your idea of green, amber, and red indications.  I am not clear on how this gets recorded (without a new state) to allow for the final human verification.

**Comment by ferventcoder** [comment]
@chocolatey/developers thoughts?

**Comment by mwrock** [comment]
I like it!

I do think it is a good idea that trusted packages be subjected to auto moderation. This may lead us to trust more packages knowing this safety net exists.

I also think its a good idea to use Pester or something similar like [serverspec](http://serverspec.org/) to itemize the checks and provide pass/fail feedback.

Will the auto-moderation user dream?

**Comment by ferventcoder** [comment]
@gep13 are you still not sold on the green / amber / red indications?

**Comment by gep13** [comment]
>@ferventcoder said...
are you still not sold on the green / amber / red indications?

Nope, I am now sold, and I have bought the t-shirt! :smile:
