### ISSUE TITLE
[[ERROR] Vagrant failed to initialize at a very early stage

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/package-verifier#103]
MOVED FROM: https://github.com/chocolatey-community/chocolatey-test-environment/issues/54

REF: https://gist.github.com/choco-bot/8a824109dec9a7e7664567efb2dd8f5f

[ERROR] Vagrant failed to initialize at a very early stage:
[ERROR] The version of powershell currently installed on this host is less than
[ERROR] the required minimum version. Please upgrade the installed version of
[ERROR] powershell to the minimum required version and run the command again.
[ERROR] Installed version: N/A
[ERROR] Minimum required version: 3

**Comment by adriens** [comment]
I'm facing the same isse https://github.com/adriens/chocolatey-schemacrawler/issues/48

**Comment by johanjanssen** [comment]
In case you need more samples, I've encountered the same: https://gist.github.com/choco-bot/ed9b52e38c865190355f4ca75b2a4159

**Comment by gep13** [comment]
@bcurran3 @adriens @johanjanssen I have set the verifier to re-run on all the packages reported here, as we believe the issue has been addressed.

Let us know if this has been cleared up.

**Comment by johanjanssen** [comment]
@gep13 yes https://chocolatey.org/packages/AdoptOpenJDK15openj9/15.0.0.36 passed. Thanks for resolving the issue so quickly!

**Comment by adriens** [comment]
All good here too 👍 
Thanks a lot @gep13 👍

**Comment by gep13** [comment]
Thanks for confirming that this has resolved your issues.

I will hold off on closing this issue until I hear from @bcurran3

**Comment by pauby** [comment]
@gep13 The root cause of the issue hasn't been identified so all we've done at the moment is get it working again for this issue. I will raise a separate issue for this (as other errors are being thrown beyond what's in this issue).

**Comment by bcurran3** [comment]
REF: https://chocolatey.org/packages/logitech-media-server/7.9.3

My package that hit the snag has since successfully pasted testing. So I'm guessing all is good.

**Comment by gep13** [comment]
@bcurran3 thanks for confirming!
