### ISSUE TITLE
Only check submitted packages that have passed validation

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/package-verifier#13]
This is https://github.com/chocolatey/chocolatey.org/issues/268

Submitted packages only.

**Comment by gep13** [comment]
As discussed, I think this makes a lot of sense :+1:

**Comment by ferventcoder** [comment]
This doesn't really need to be the case as this is somewhat fast.

**Comment by ferventcoder** [comment]
Closing for now.

**Comment by gep13** [comment]
@ferventcoder there will still be certain packages, for example, Visual Studio, that would benefit from holding until validation has passed, right?

**Comment by ferventcoder** [comment]
Right now it's not super expensive to run the verifier - so I see it as a pre optimization now - where both could be running in parallel instead.
