### ISSUE TITLE
chocolatey package validate (auto moderate) command?

### ISSUE THREAD

**Issue by DanAtkinson** [chocolatey/package-verifier#2]
Hi!

I'm not sure where the best place would be to ask this. Perhaps not here. Perhaps in the main chocolatey repo...

I'm wondering if you would expect a user to be able to validate that their package is correct by uploading it?

So, whereas I would currently just `choco push` the package, would it be possible to extend it to `choco validate`?

Concerns would be that it is open to abuse, but then I would wonder whether a 'lite' validation might be able to be incorporated into chocolatey itself.

Thanks, Dan

**Comment by ferventcoder** [comment]
So think push could give them the same thing.

**Comment by ferventcoder** [comment]
In that whether trusted or untrusted, if the package doesn't pass the automated bits, the user will be notified and the package held up.

**Comment by Zougi** [comment]
I came here to post a similar suggestion I suppose. What if this 'lite' validation is based on the number of stars, the github repo of the package, has!?

**Comment by ferventcoder** [comment]
@Zougi tell me how we trace that the package comes from the github repository and I will be more open to it. Traceability is hard, even with humans involved.

**Comment by Zougi** [comment]
I never developed a package for choco but according to the doc at some point, to publish a package you have to write a chocolateyInstall.ps1 with the url to the repository of the package !?

The service that checks if a package is trusted or not could parse this url. Get the stargazers_count object from https://api.github.com/repos/[account]/[repo] (ie: https://api.github.com/repos/chocolatey/choco)

And if there are more than ie 200 starts, package would be semi-trusted:
I mean it would be available to the community but waiting for a real human to check if package is really to be trusted.

I believe it's also feasible with other services like sourceforge or codeplex.

**Comment by ferventcoder** [comment]
> I never developed a package for choco but according to the doc at some point, to publish a package you have to write a chocolateyInstall.ps1 with the url to the repository of the package !?

If you have software you are not allowed to distribute, you usually use the chocolateyInstall.ps1 to add instructions on where to get the installer or zip archive.

> And if there are more than ie 200 starts, package would be semi-trusted:
I mean it would be available to the community but waiting for a real human to check if package is really to be trusted.

> I believe it's also feasible with other services like sourceforge or codeplex.

Understanding what it is that makes a package trusted would probably be more helpful. When the maintainer of the software is also the package maintainer, then it's a slam dunk on that. The other way folks get packages to a trusted status is to continuously put up a package that has no issues and they themselves earn trust of moderators and community.

**Comment by ferventcoder** [comment]
For the original questions @DanAtkinson I think you wanted to know if the validation would be added to choco and the answer is yes - as part of choco pack. Some of those things - and those can be found in https://github.com/chocolatey/package-validator.

**Comment by DanAtkinson** [comment]
Hi Rob,

Thanks for letting me know. :)

Dan

**Comment by ferventcoder** [comment]
I think we can close this - respond otherwise if you want this reopened.
