### ISSUE TITLE
Write out invalid JSON returned from GitHub

### ISSUE THREAD

**Issue by gep13** [chocolatey/package-verifier#23]
The package verifier is seeing a number of issues like this:

`There are 1 exceptions of 'ApiException'.Octokit.ApiException: Problems parsing JSON`

In order to help track down the root cause, print out the invalid JSON as part of logging.

**Comment by ferventcoder** [comment]
We also want to bump the email schedule to every 15 minutes instead of every 5

**Comment by ferventcoder** [comment]
@gep13 the problem here is that the JSON is not invalid. 

Plus I'm not really sure you want that in an email. It could be hundreds of lines. I'm going to go with just the package that failed for now (and maybe print the gist data to a file).

**Comment by ferventcoder** [comment]
For now just stating the name of the package and version.

**Comment by ferventcoder** [comment]
Also https://github.com/octokit/octokit.net/issues/967

**Comment by gep13** [comment]
@ferventcoder so what is returned from the call to create gist?  I would have expected just the status of the call, i.e. succeeded, creation time, etc.  Is it returning all the content of the gist that was just created?  If so, I see why you are suggesting we don't write that out.
