### ISSUE TITLE
Unable to resolve dependency for packages that depends on NuGet.org dependencies

### ISSUE THREAD

**Issue by EoflaOE** [chocolatey/package-verifier#74]
The package verifier shouldn't fail when it can't find a dependency that only exists on NuGet and didn't exist on Chocolatey. As my application which is not listed failed the verifucation because of dependencies that only exist on NuGet, it is impossible to accept the package.

Can the verifier be updated so it can add both NuGet and Chocolatey repositories?

**Comment by gep13** [comment]
@EoflaOE Chocolatey is an application package manager, it deals with the dependencies that exists between packages at the installed applications level, not at the project level for assembly required to compile the application.  

For example, a package for an application might take a dependency on the package for the Visual C++ redistributable application.  

At installation time, this application dependency would be installed, which would then allow the parent package to install correctly and for it's application to be runnable.

The dependencies that you have on your [package](https://chocolatey.org/packages/KS/0.0.6.13) seem to be those that would be required for the application to compile correctly.  This is not what Chocolatey is intended for.  The expectation would be that these assemblies would be collected into some deployable artifact, which would then be installed by Chocolatey.

Does that make sense?

**Comment by EoflaOE** [comment]
@gep13 Yes, but it's a .NET application which require dependencies' DLLs to be in the same directory as in the executable location. If the DLLs are not in the same location as the .NET application, it would fail to launch, so I think it's a dependency for both .NET compilation and runtime process.

Any suggestions?

**Comment by mkevenaar** [comment]
@EoflaOE Would it be possible to ship those DLL files with your (compiled) application, e.g. using a ZIP archive or with an (msi) installer?

**Comment by gep13** [comment]
@EoflaOE I completely understand what you are saying, but I have to agree with @mkevenaar here.  NuGet dependencies are resolved at the time of compilation for the application that you are creating, using either `nuget restore` or `dotnet restore`.  They are not intended to be shipped as part of the dependencies for a Chocolatey package.  Assuming that you have the distribution rights for these assemblies, you would ship them within an installer that you create, or as part of the contents of the Chocolatey package.

**Comment by EoflaOE** [comment]
@gep13 and @mkevenaar Thanks. I will ship it with the installer. But how did some Chocolate packages come with "nupkg?"

**Comment by EoflaOE** [comment]
Case closed, however I have met its accomplice...
