### ISSUE TITLE
SLA Link outdated on Contributing Guidelines

### ISSUE THREAD

**Issue by EoflaOE** [chocolatey/package-verifier#75]
On the contributing guideline page, there is a link to the SLA form that everybody should apply. It appears to be out of date, because when I went to it, it returns an error message saying that the form didn't exist.

The link that didn't work is https://www.clahub.com/agreements/chocolatey/package-verifier

**Comment by mkevenaar** [comment]
@EoflaOE I think you are talking about the CLA, right?

**Comment by EoflaOE** [comment]
Yes. It got outdated

**Comment by mkevenaar** [comment]
@EoflaOE I think the same as in https://github.com/chocolatey/package-validator/issues/158#issuecomment-277892802 is valid.

@ferventcoder Could you elaborate on this?

**Comment by EoflaOE** [comment]
@mkevenaar Thanks.

**Comment by ferventcoder** [comment]
yeppers, same as with validator.
