### ISSUE TITLE
dotnetfx install failed

### ISSUE THREAD

**Issue by EoflaOE** [chocolatey/package-verifier#76]
I have resolved the issue about the previous NuGet.org dependency failure by following the docs, but when I have depended on "dotnetfx 4.7.2," I have packed it and then uploaded it to Chocolatey to see if I can get past the verification.

However, the verification failed because of dotnetfx not installing because of the error as specified in https://gist.github.com/choco-bot/67467569d304aed11a5141a0cdd934ca#file-install-txt-L1463 | Line 1463.

The problem is that if I have removed the dependency, then users will have to install .NET Framework 4.7.2 manually or through Chocolatey, which is what I don't want. I want my package and a dependency to be installed without errors.

**Comment by mkevenaar** [comment]
@EoflaOE That's a known thing. You need to ask for an exemption on your package. This will be fixed in the future when the package-verifier supports reboots.

**Comment by EoflaOE** [comment]
Thanks @mkevenaar! I will ask for exempt, because it requires reboot.

**Comment by gep13** [comment]
@EoflaOE I understand why you might have created this issue here, but in future, can you use the package moderation page on chocolatey.org to ask questions about the package moderation process?  Or, you can ask questions in the Gitter room here: https://gitter.im/chocolatey/chocolatey.org

**Comment by gep13** [comment]
@EoflaOE actually, looks like you have asked a question there already :+1:
