### ISSUE TITLE
Set TLS 1.2 protocol to allow communication with chocolatey.org

### ISSUE THREAD

**Issue by pauby** [chocolatey/package-verifier#80]
The removal of TLS 1.2 on the chocolatey.org website has stopped the Package Verifier from being able to download chocolatey in the normal way. 

We've confirmed that the Package Verifier virtual image has the correct cipher suites. The protocol just needs to be enabled.

**Comment by gep13** [comment]
@pauby are you happy to get this released, and then we can close this out?

**Comment by gep13** [comment]
@pauby I am fairly sure that this has been released, so I am going to go ahead and close out this issue, let me know if you have any questions.

**Comment by pauby** [comment]
This hasn't been publicly released as yet. It will be released when I submit the new package code.

**Comment by pauby** [comment]
This has been released now.
