### ISSUE TITLE
404 error for Boinc

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey/package-verifier#85]
Hello, 
Each time i run the verification test my Boinc package, i get a 404 error, but it works on my CI, on my computer and orher computers.
So the problem seems always on the verifier.
I've added the KB2919355 package, but it don't solve anything.

Thank you

**Comment by FullofQuarks** [comment]
Relevant [Gist](https://gist.github.com/FullofQuarks/4f7a110295a8c2b4d59f3892d0b5e821#file-install-txt-L926)
Error: The request was aborted: Could not create SSL/TLS secure channel.

In here just providing some additional details and logs

**Comment by ferventcoder** [comment]
I don't believe this is the proper place for this issue, I want to say if you are the package maintainer you are given an email that has (hopefully) clear instructions on the process of talking directly to the moderators and requesting an exemption. Hopefully you've found that (apologies I'm just now coming across this issue).
