### ISSUE TITLE
Create Chocolatey Package

### ISSUE THREAD

**Issue by pauby** [chocolatey/package-verifier#92]
A Chocolatey package should be created to allow easy deployment and upgrades.

**Comment by AdmiringWorm** [comment]
> NOTE: This will include changes to the UppercuT build to create the Chocolatey package as part of the overall build process.

So not going to change over to using Cake 😆

**Comment by gep13** [comment]
>@AdmiringWorm said...
So not going to change over to using Cake 😆

Not in this scope of work, no, but there is a larger scope of work where I would like to get to this, yes 😄

**Comment by pauby** [comment]
The PR just submitted is for Package Verifier but we need to look at how we are going to create a package for Package Verifier Existing (as this will need two sets of package files in the `nuget` folder).
